from pathlib import Path
import re, sys

root=Path(sys.argv[1])
java=root/"app/src/main/java/com/hakan/jarvis/HybridActivity.java"
manifest=root/"app/src/main/AndroidManifest.xml"
gradle=root/"app/build.gradle"

s=java.read_text()

def rep(name, old, new):
    global s
    if old not in s:
        raise SystemExit("PATCH_MISSING:"+name)
    s=s.replace(old,new,1)

rep("field",'    private boolean waitingFinal,spokenCommand,pendingSpoken;\n','    private boolean waitingFinal,spokenCommand,pendingSpoken,pendingWakeSetup;\n')
rep("oncreate",'    @Override protected void onCreate(Bundle state) {\n        prefs=getSharedPreferences("jarvis_hybrid",MODE_PRIVATE);\n','    @Override protected void onCreate(Bundle state) {\n        final boolean wakeLaunch=getIntent()!=null&&getIntent().getBooleanExtra(WakeWordService.EXTRA_WAKE_TRIGGER,false);\n        if(wakeLaunch){try{if(Build.VERSION.SDK_INT>=27){setShowWhenLocked(true);setTurnScreenOn(true);}else getWindow().addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON|WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);}catch(Exception ignored){}}\n        prefs=getSharedPreferences("jarvis_hybrid",MODE_PRIVATE);\n')
s=s.replace('JARVIS 1.6.4.17 · CONTEXT CHAIN SAFE','JARVIS 1.7.0 · ALWAYS-ON WAKE WORD',1)
rep("heard",'        heard=new TextView(this);heard.setTextColor(0xffeaf4ff);heard.setText("Duyduğum: —");root.addView(heard);\n','        heard=new TextView(this);heard.setTextColor(0xffeaf4ff);heard.setText("Duyduğum: —");root.addView(heard);\n        final TextView wakeStatus=new TextView(this);wakeStatus.setTextColor(0xff99bacb);wakeStatus.setText("Wake word: "+(prefs.getBoolean("wake_enabled",false)?(WakeWordDetector.hasEnrollment(this)?"AÇIK · ekran kapalı dinleme hazır":"AÇIK · ses kalibrasyonu gerekli"):"KAPALI"));root.addView(wakeStatus);\n')

marker='        phone=new PhoneActions(this,new PhoneActions.Host()'
pos=s.find(marker)
if pos<0: raise SystemExit("PATCH_MISSING:phone")
end=s.find("\n",pos)
line=s[pos:end].replace('Telefon komutu · 1.6.2','Telefon komutu · 1.7.0')
s=s[:pos]+line+'\n        if(prefs.getBoolean("wake_enabled",false)&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED&&WakeWordDetector.hasEnrollment(this))WakeWordService.start(this);\n        if(wakeLaunch)handler.postDelayed(new Runnable(){public void run(){handleWakeLaunch();}},450);'+s[end:]

rep("lifecycle",'    @Override protected void onResume(){super.onResume();updateHybridStatus();if(!registered){try{registerReceiver(networkReceiver,new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));registered=true;}catch(Exception ignored){}}}\n    @Override protected void onPause(){if(phone!=null)phone.pause();if(registered){try{unregisterReceiver(networkReceiver);}catch(Exception ignored){}registered=false;}stopRecognition();if(voice!=null)voice.stop();deferredAction=null;chainedNext="";super.onPause();}\n','    @Override protected void onResume(){super.onResume();updateHybridStatus();if(!registered){try{registerReceiver(networkReceiver,new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));registered=true;}catch(Exception ignored){}}}\n    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(intent!=null&&intent.getBooleanExtra(WakeWordService.EXTRA_WAKE_TRIGGER,false))handler.postDelayed(new Runnable(){public void run(){handleWakeLaunch();}},250);}\n    private void handleWakeLaunch(){if(dead||voice==null)return;WakeWordService.clearWakeNotification(this);Intent i=getIntent();if(i!=null)i.removeExtra(WakeWordService.EXTRA_WAKE_TRIGGER);stopRecognition();voice.beginTurn();answer.setText("Buradayım efendim. Komutunuzu dinliyorum.");meta.setText("Always-On Wake Word · 1.7.0");say("","wake",new Runnable(){public void run(){beginListening();}});}\n    @Override protected void onPause(){if(phone!=null)phone.pause();if(registered){try{unregisterReceiver(networkReceiver);}catch(Exception ignored){}registered=false;}stopRecognition();if(voice!=null)voice.stop();deferredAction=null;chainedNext="";if(prefs!=null&&prefs.getBoolean("wake_enabled",false))WakeWordService.resume(this);super.onPause();}\n')

rep("settings_controls",'        final CheckBox offline=new CheckBox(this);offline.setText("Yalnızca çevrimdışı kullan");offline.setChecked(prefs.getBoolean("force_offline",false));layout.addView(offline);\n        TextView info=new TextView(this);info.setText("Çevrimdışı ses tanıma, telefonda Türkçe model desteği gerektirir. Yazılı komutlar her zaman kullanılabilir.\\n\\nDoğal Türkçe erkek sesi aktiftir. İnternette ayrıntılı yanıtlar seslendirilir; çevrimdışıyken aynı sesin gömülü komut yanıtları kullanılır. Android sistem TTS kullanılmaz.");layout.addView(info);\n','        final CheckBox offline=new CheckBox(this);offline.setText("Yalnızca çevrimdışı kullan");offline.setChecked(prefs.getBoolean("force_offline",false));layout.addView(offline);\n        final CheckBox wake=new CheckBox(this);wake.setText("Ekran kapalıyken ‘Jarvis’ ile uyan");wake.setChecked(prefs.getBoolean("wake_enabled",false));layout.addView(wake);\n        TextView wakeInfo=new TextView(this);wakeInfo.setText(WakeWordDetector.hasEnrollment(this)?"Wake word sesi öğrenildi. Kayıtlar yalnızca uygulamanın özel depolamasında tutulur.":"İlk kullanımda JARVIS sesinizi üç kez dinleyerek kişisel wake-word kalibrasyonu yapar. İnternet gerekmez.");layout.addView(wakeInfo);\n        layout.addView(button("JARVIS SESİNİ ÖĞRET / YENİDEN KALİBRE ET",new View.OnClickListener(){public void onClick(View v){prefs.edit().putBoolean("wake_enabled",true).apply();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){pendingWakeSetup=true;requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},813);}else startWakeEnrollment();}}));\n        TextView info=new TextView(this);info.setText("Çevrimdışı ses tanıma, telefonda Türkçe model desteği gerektirir. Yazılı komutlar her zaman kullanılabilir.\\n\\nDoğal Türkçe erkek sesi aktiftir. İnternette ayrıntılı yanıtlar seslendirilir; çevrimdışıyken aynı sesin gömülü komut yanıtları kullanılır. Android sistem TTS kullanılmaz.");layout.addView(info);\n')

rep("settings_save",'        new AlertDialog.Builder(this).setTitle("Hibrit ayarlar").setView(settingsScroll).setPositiveButton("Kaydet",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){String c=city.getText().toString().trim();prefs.edit().putString("city",c.length()==0?"Kahramanmaraş":c).putBoolean("force_offline",offline.isChecked()).putBoolean("cloud_voice",cloud.isChecked()).apply();cancelWork();stopRecognition();voice.beginTurn();updateHybridStatus();say("","settings_saved",null);}}).setNegativeButton("Vazgeç",null).show();\n','        new AlertDialog.Builder(this).setTitle("Hibrit ayarlar").setView(settingsScroll).setPositiveButton("Kaydet",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){String c=city.getText().toString().trim();prefs.edit().putString("city",c.length()==0?"Kahramanmaraş":c).putBoolean("force_offline",offline.isChecked()).putBoolean("cloud_voice",cloud.isChecked()).putBoolean("wake_enabled",wake.isChecked()).apply();cancelWork();stopRecognition();voice.beginTurn();updateHybridStatus();if(!wake.isChecked()){WakeWordService.stop(HybridActivity.this);say("","settings_saved",null);}else if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){pendingWakeSetup=true;requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},813);}else if(!WakeWordDetector.hasEnrollment(HybridActivity.this))startWakeEnrollment();else{WakeWordService.start(HybridActivity.this);say("","settings_saved",null);}}}).setNegativeButton("Vazgeç",null).show();\n')

rep("enrollment",'    private void clearLegacyLabels(ViewGroup group){','    private void startWakeEnrollment(){WakeWordService.stop(this);stopRecognition();if(voice!=null)voice.stop();WakeWordEnrollment.start(this,new WakeWordEnrollment.Listener(){public void done(boolean ok,String detail){if(dead)return;if(ok){prefs.edit().putBoolean("wake_enabled",true).apply();answer.setText("Wake word hazır\\n\\nArtık ekran kapalıyken ‘Jarvis’ dediğinizde JARVIS uyanmayı deneyecek.");meta.setText(detail+" · 1.7.0");WakeWordService.start(HybridActivity.this);if(voice!=null){voice.beginTurn();say("","settings_saved",null);}}else{prefs.edit().putBoolean("wake_enabled",false).apply();answer.setText("Wake word kalibrasyonu tamamlanamadı\\n\\n"+detail);meta.setText("Hibrit Ayarlar > JARVIS SESİNİ ÖĞRET ile yeniden deneyebilirsiniz.");}}});}\n    private void clearLegacyLabels(ViewGroup group){')
rep("begin",'    private void beginListening(){\n        if(voice!=null)voice.beginTurn();if(phone!=null)phone.cancel();cancelWork();deferredAction=null;\n','    private void beginListening(){\n        WakeWordService.pause(this,45000);\n        if(voice!=null)voice.beginTurn();if(phone!=null)phone.cancel();cancelWork();deferredAction=null;\n')
rep("activity_result",'        if(requestCode==812){if(resultCode==RESULT_OK&&data!=null)acceptSpeech(data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS),null);else{voice.beginTurn();say("","cancel",null);}return;}\n','        if(requestCode==812){WakeWordService.resume(this);if(resultCode==RESULT_OK&&data!=null)acceptSpeech(data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS),null);else{voice.beginTurn();say("","cancel",null);}return;}\n')
rep("permission",'    @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] grants){if(phone!=null&&phone.permissions(code,grants))return;if(code==810){if(grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)beginListening();else local("Mikrofon izni kapalı","YAZ düğmesiyle komut verebilirsiniz. Telefonun uygulama izinlerinden mikrofonu açabilirsiniz.");return;}super.onRequestPermissionsResult(code,permissions,grants);}\n','    @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] grants){if(phone!=null&&phone.permissions(code,grants))return;if(code==810){if(grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)beginListening();else local("Mikrofon izni kapalı","YAZ düğmesiyle komut verebilirsiniz. Telefonun uygulama izinlerinden mikrofonu açabilirsiniz.");return;}if(code==813){boolean ok=grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED;if(ok&&pendingWakeSetup){pendingWakeSetup=false;startWakeEnrollment();}else{pendingWakeSetup=false;prefs.edit().putBoolean("wake_enabled",false).apply();local("Wake word kapalı","Ekran kapalı dinleme için mikrofon izni gerekir.");}return;}super.onRequestPermissionsResult(code,permissions,grants);}\n')
rep("failure",'    private void recognitionFailure(int code){stopRecognition();if(dead)return;recognitionStatus.setText("DİNLEME SONA ERDİ · "+RecognitionConfig.error(code));meta.setText("Tanıma kodu: "+code+" · Son duyulan metin yukarıda.");say("",code==9?"mic_denied":"speech_error",null);}\n','    private void recognitionFailure(int code){stopRecognition();WakeWordService.resume(this);if(dead)return;recognitionStatus.setText("DİNLEME SONA ERDİ · "+RecognitionConfig.error(code));meta.setText("Tanıma kodu: "+code+" · Son duyulan metin yukarıda.");say("",code==9?"mic_denied":"speech_error",null);}\n')
rep("results",'                public void onResults(Bundle b){if(recognitionId!=recognitionEpoch)return;ArrayList<String> texts=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);float[] scores=b.getFloatArray(SpeechRecognizer.CONFIDENCE_SCORES);stopRecognition();recognitionStatus.setText("KONUŞMA ALINDI");acceptSpeech(texts,scores);}\n','                public void onResults(Bundle b){if(recognitionId!=recognitionEpoch)return;ArrayList<String> texts=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);float[] scores=b.getFloatArray(SpeechRecognizer.CONFIDENCE_SCORES);stopRecognition();WakeWordService.resume(HybridActivity.this);recognitionStatus.setText("KONUŞMA ALINDI");acceptSpeech(texts,scores);}\n')

java.write_text(s)

m=manifest.read_text()
m=re.sub(r'android:versionCode="\d+"','android:versionCode="83"',m,count=1)
m=re.sub(r'android:versionName="[^"]+"','android:versionName="1.7.0-wakeword1"',m,count=1)
if 'FOREGROUND_SERVICE_MICROPHONE' not in m:
    m=m.replace('  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />\n','  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />\n  <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MICROPHONE" />\n',1)
m=m.replace('<activity android:name="com.hakan.jarvis.HybridActivity" android:exported="true" android:windowSoftInputMode="adjustResize">','<activity android:name="com.hakan.jarvis.HybridActivity" android:exported="true" android:launchMode="singleTop" android:showWhenLocked="true" android:turnScreenOn="true" android:windowSoftInputMode="adjustResize">',1)
if 'WakeWordService' not in m:
    m=m.replace('    <service android:name=".AlarmRingService" android:exported="false" android:foregroundServiceType="mediaPlayback" />\n','    <service android:name=".AlarmRingService" android:exported="false" android:foregroundServiceType="mediaPlayback" />\n    <service android:name=".WakeWordService" android:exported="false" android:foregroundServiceType="microphone" />\n    <receiver android:name=".WakeWordBootReceiver" android:exported="true"><intent-filter><action android:name="android.intent.action.BOOT_COMPLETED"/><action android:name="android.intent.action.MY_PACKAGE_REPLACED"/></intent-filter></receiver>\n',1)
manifest.write_text(m)

g=gradle.read_text()
g=re.sub(r'versionCode\s+\d+','versionCode 83',g,count=1)
g=re.sub(r"versionName\s+'[^']+'","versionName '1.7.0-wakeword1'",g,count=1)
gradle.write_text(g)

print("PATCH_OK")
