plugins { id 'com.android.application' }

android {
    namespace 'com.hakan.voxelcraft'
    compileSdk 35

    defaultConfig {
        applicationId 'com.hakan.voxelcraft'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
