package com.hakan.jarvis;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;
public final class WakeWordService extends Service{
 public static final String ACTION_START="com.hakan.jarvis.WAKE_START",ACTION_STOP="com.hakan.jarvis.WAKE_STOP",ACTION_PAUSE="com.hakan.jarvis.WAKE_PAUSE",ACTION_RESUME="com.hakan.jarvis.WAKE_RESUME",EXTRA_WAKE="jarvis_wake";private static final String CHANNEL="jarvis_wake_channel";private static final int NOTIFICATION_ID=1700;private final Handler main=new Handler(Looper.getMainLooper());private OpenWakeWordDetector detector;private PowerManager.WakeLock cpuLock;private boolean paused;
 private final BroadcastReceiver control=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String a=i==null?"":i.getAction();if(ACTION_PAUSE.equals(a)){paused=true;stopDetector();update("Komut mikrofonu aktif · wake beklemede");}else if(ACTION_RESUME.equals(a)){if(enabled(WakeWordService.this)){paused=false;startDetector();}}else if(ACTION_STOP.equals(a)){shutdown();stopForeground(true);stopSelf();}}};
 public static boolean enabled(Context c){return c.getSharedPreferences("jarvis_hybrid",Context.MODE_PRIVATE).getBoolean("wake_enabled",true);}
 private static void signal(Context c,String action){try{c.sendBroadcast(new Intent(action).setPackage(c.getPackageName()));}catch(Exception ignored){}}
 public static void ensureStarted(Context c){if(!enabled(c)||c.checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)return;Intent i=new Intent(c,WakeWordService.class).setAction(ACTION_START);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 public static void stop(Context c){signal(c,ACTION_STOP);try{c.stopService(new Intent(c,WakeWordService.class));}catch(Exception ignored){}}
 public static void pause(Context c){signal(c,ACTION_PAUSE);}
 public static void resume(Context c){if(enabled(c))signal(c,ACTION_RESUME);}
 @Override public void onCreate(){super.onCreate();createChannel();try{registerReceiver(control,new IntentFilter(ACTION_PAUSE));registerReceiver(control,new IntentFilter(ACTION_RESUME));registerReceiver(control,new IntentFilter(ACTION_STOP));}catch(Exception ignored){}PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);if(pm!=null){cpuLock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"JARVIS:wakeword");cpuLock.setReferenceCounted(false);}}
 @Override public int onStartCommand(Intent intent,int flags,int startId){startForeground(NOTIFICATION_ID,notification("'Jarvis' demeni bekliyor"));if(!enabled(this)){stopSelf();return START_NOT_STICKY;}paused=false;startDetector();return START_STICKY;}
 private void startDetector(){if(paused||!enabled(this)||checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)return;if(cpuLock!=null&&!cpuLock.isHeld())try{cpuLock.acquire();}catch(Exception ignored){}if(detector==null)detector=new OpenWakeWordDetector(this,0.28f,0.62f,4200L);if(detector.isRunning())return;update("Offline wake aktif · 'Jarvis' demeni bekliyor");detector.start(new OpenWakeWordDetector.Listener(){public void onDetected(float score){wake(score);}public void onError(String m){update("Wake motoru durdu · JARVIS'i açın");main.postDelayed(new Runnable(){public void run(){if(!paused)startDetector();}},4000);}});}
 private void stopDetector(){if(detector!=null)detector.stop();if(cpuLock!=null&&cpuLock.isHeld())try{cpuLock.release();}catch(Exception ignored){}}
 private void shutdown(){paused=true;if(detector!=null){detector.release();detector=null;}if(cpuLock!=null&&cpuLock.isHeld())try{cpuLock.release();}catch(Exception ignored){}main.removeCallbacksAndMessages(null);}
 private void wake(float score){if(paused)return;paused=true;stopDetector();update("Uyandım · komut dinleme açılıyor");Intent open=new Intent(this,HybridActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP).putExtra(EXTRA_WAKE,true).putExtra("wake_score",score);try{startActivity(open);}catch(Exception e){PendingIntent pi=PendingIntent.getActivity(this,1700,open,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0));NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null)nm.notify(NOTIFICATION_ID,notificationWithIntent("JARVIS seni duydu · komut için dokun",pi));}main.postDelayed(new Runnable(){public void run(){if(paused){paused=false;startDetector();}}},18000);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null){NotificationChannel c=new NotificationChannel(CHANNEL,"JARVIS Wake Word",NotificationManager.IMPORTANCE_LOW);c.setDescription("Ekran kapalıyken çevrimdışı Jarvis wake word dinleme");c.setSound(null,null);nm.createNotificationChannel(c);}}}
 private Notification notification(String text){Intent open=new Intent(this,HybridActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent pi=PendingIntent.getActivity(this,1,open,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0));return notificationWithIntent(text,pi);}
 private Notification notificationWithIntent(String text,PendingIntent pi){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setContentTitle("JARVIS · Always-On").setContentText(text).setSmallIcon(android.R.drawable.ic_btn_speak_now).setOngoing(true).setOnlyAlertOnce(true).setContentIntent(pi).setCategory(Notification.CATEGORY_SERVICE);if(Build.VERSION.SDK_INT<26)b.setPriority(Notification.PRIORITY_LOW);return b.build();}
 private void update(String text){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null)nm.notify(NOTIFICATION_ID,notification(text));}
 @Override public void onDestroy(){try{unregisterReceiver(control);}catch(Exception ignored){}shutdown();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}