package com.hakan.jarvis;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.content.res.AssetFileDescriptor;import android.media.*;import android.os.*;
public final class WakeWordService extends Service{
 public static final String ACTION_START="com.hakan.jarvis.WAKE_START",ACTION_STOP="com.hakan.jarvis.WAKE_STOP",ACTION_PAUSE="com.hakan.jarvis.WAKE_PAUSE",ACTION_RESUME="com.hakan.jarvis.WAKE_RESUME",EXTRA_WAKE="jarvis_wake",EXTRA_WAKE_ACKED="jarvis_wake_acked";private static final String CHANNEL="jarvis_wake_channel";private static final int NOTIFICATION_ID=1700;private final Handler main=new Handler(Looper.getMainLooper());private OpenWakeWordDetector detector;private PowerManager.WakeLock cpuLock,handoffLock,screenLock;private MediaPlayer wakePlayer;private AudioManager audio;private boolean paused,screenOff,speechLease;private int detectorStarts,detectorErrors;private float globalMaxScore,offMaxScore,offMaxRms;private int offMaxPeak;private long offFrames,offLastFrame;private String lastOff="OFF yok";
 private final AudioManager.OnAudioFocusChangeListener focusListener=new AudioManager.OnAudioFocusChangeListener(){public void onAudioFocusChange(int f){}};
 private final BroadcastReceiver control=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String a=i==null?"":i.getAction();String why=i==null?"?":i.getStringExtra("forensic_reason");if(ACTION_PAUSE.equals(a)){if("wake_handoff".equals(why)||"speech_begin".equals(why))speechLease=true;JarvisForensics.event(WakeWordService.this,"W","SERVICE PAUSE reason="+why+" lease="+speechLease);paused=true;stopDetector("pause:"+why);update("Komut mikrofonu aktif · wake beklemede");}else if(ACTION_RESUME.equals(a)){speechLease=false;JarvisForensics.event(WakeWordService.this,"W","SERVICE RESUME reason="+why+" lease=false");if(enabled(WakeWordService.this)){paused=false;startDetector("resume:"+why);}}else if(Intent.ACTION_SCREEN_OFF.equals(a)){JarvisForensics.event(WakeWordService.this,"L","SCREEN_OFF running="+(detector!=null&&detector.isRunning()));screenOff=true;beginOffWindow();writeDiag();}else if(Intent.ACTION_SCREEN_ON.equals(a)){JarvisForensics.event(WakeWordService.this,"L","SCREEN_ON running="+(detector!=null&&detector.isRunning()));finishOffWindow();screenOff=false;writeDiag();}else if(ACTION_STOP.equals(a)){JarvisForensics.event(WakeWordService.this,"W","SERVICE STOP reason="+why);shutdown();stopForeground(true);stopSelf();}}};
 public static boolean enabled(Context c){return c.getSharedPreferences("jarvis_hybrid",Context.MODE_PRIVATE).getBoolean("wake_enabled",true);}
 private static void signal(Context c,String action,String reason){try{c.sendBroadcast(new Intent(action).setPackage(c.getPackageName()).putExtra("forensic_reason",reason));}catch(Exception ignored){}}
 public static void ensureStarted(Context c){if(!enabled(c)||c.checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)return;Intent i=new Intent(c,WakeWordService.class).setAction(ACTION_START);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 public static void stop(Context c){signal(c,ACTION_STOP,"api_stop");try{c.stopService(new Intent(c,WakeWordService.class));}catch(Exception ignored){}}
 public static void pause(Context c){pause(c,"unspecified");}public static void pause(Context c,String reason){signal(c,ACTION_PAUSE,reason);}
 public static void resume(Context c){resume(c,"unspecified");}public static void resume(Context c,String reason){if(enabled(c))signal(c,ACTION_RESUME,reason);}
 @Override public void onCreate(){super.onCreate();JarvisForensics.event(this,"L","service.onCreate");createChannel();try{IntentFilter f=new IntentFilter();f.addAction(ACTION_PAUSE);f.addAction(ACTION_RESUME);f.addAction(ACTION_STOP);f.addAction(Intent.ACTION_SCREEN_OFF);f.addAction(Intent.ACTION_SCREEN_ON);registerReceiver(control,f);}catch(Exception ignored){}PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);if(pm!=null){cpuLock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"JARVIS:wakeword");cpuLock.setReferenceCounted(false);handoffLock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"JARVIS:wake-handoff");handoffLock.setReferenceCounted(false);screenLock=pm.newWakeLock(PowerManager.SCREEN_DIM_WAKE_LOCK|PowerManager.ACQUIRE_CAUSES_WAKEUP|PowerManager.ON_AFTER_RELEASE,"JARVIS:wake-screen");screenLock.setReferenceCounted(false);}audio=(AudioManager)getSystemService(AUDIO_SERVICE);try{PowerManager p=(PowerManager)getSystemService(POWER_SERVICE);screenOff=p!=null&&!p.isInteractive();}catch(Exception ignored){}}
 @Override public int onStartCommand(Intent intent,int flags,int startId){JarvisForensics.event(this,"L","service.onStartCommand id="+startId+" flags="+flags+" action="+(intent==null?"null":intent.getAction()));startForeground(NOTIFICATION_ID,notification("'Hey Jarvis' demeni bekliyor"));if(!enabled(this)){stopSelf();return START_NOT_STICKY;}paused=false;startDetector("service_start");return START_STICKY;}
 private void startDetector(){startDetector("unspecified");}private void startDetector(String reason){if(paused||!enabled(this)||checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){JarvisForensics.event(this,"W","startDetector BLOCK reason="+reason+" paused="+paused+" enabled="+enabled(this)+" micPerm="+(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED));return;}if(cpuLock!=null&&!cpuLock.isHeld())try{cpuLock.acquire();}catch(Exception ignored){}if(detector==null)detector=new OpenWakeWordDetector(this,0.30f,0.48f,3800L);if(detector.isRunning()){JarvisForensics.event(this,"W","startDetector ignored running reason="+reason);return;}detectorStarts++;JarvisForensics.event(this,"W","startDetector #"+detectorStarts+" reason="+reason);update("Hey Jarvis · FORENSIC dinleme");detector.start(new OpenWakeWordDetector.Listener(){public void onDetected(float score){wake(score);}public void onError(String m){detectorErrors++;JarvisForensics.event(WakeWordService.this,"W","listener.onError #"+detectorErrors+" "+m);writeDiag();main.postDelayed(new Runnable(){public void run(){if(!paused)restartDetector("listener_error");}},1800);}});main.removeCallbacks(diagTick);main.postDelayed(diagTick,1200);}
 private void stopDetector(){stopDetector("unspecified");}private void stopDetector(String reason){JarvisForensics.event(this,"W","stopDetector reason="+reason+" running="+(detector!=null&&detector.isRunning()));main.removeCallbacks(diagTick);captureTotals();if(detector!=null)detector.stop();if(cpuLock!=null&&cpuLock.isHeld())try{cpuLock.release();}catch(Exception ignored){}}private void restartDetector(){restartDetector("unspecified");}private void restartDetector(final String reason){if(paused){JarvisForensics.event(this,"W","restart BLOCK paused reason="+reason);return;}JarvisForensics.event(this,"W","restartDetector reason="+reason);stopDetector("restart:"+reason);main.postDelayed(new Runnable(){public void run(){if(!paused)startDetector("restart:"+reason);}},500);}private final Runnable diagTick=new Runnable(){public void run(){if(paused)return;captureTotals();writeDiag();main.postDelayed(this,2500);}};private String sourceName(int s){if(s==MediaRecorder.AudioSource.MIC)return "MIC";if(s==MediaRecorder.AudioSource.VOICE_RECOGNITION)return "VR";if(s==MediaRecorder.AudioSource.VOICE_COMMUNICATION)return "VC";return "?";}private void beginOffWindow(){OpenWakeWordDetector d=detector;offLastFrame=d==null?0:d.getFrameCount();offFrames=0;offMaxScore=0f;offMaxRms=0f;offMaxPeak=0;if(d!=null)d.resetPeakScore();lastOff="OFF ölçülüyor";}private void captureTotals(){OpenWakeWordDetector d=detector;if(d==null)return;if(d.getMaxScore()>globalMaxScore)globalMaxScore=d.getMaxScore();if(screenOff){long cur=d.getFrameCount();long delta=cur>=offLastFrame?cur-offLastFrame:cur;if(delta>0)offFrames+=delta;offLastFrame=cur;if(d.getLastScore()>offMaxScore)offMaxScore=d.getLastScore();if(d.getMaxScore()>offMaxScore)offMaxScore=d.getMaxScore();if(d.getLastRms()>offMaxRms)offMaxRms=d.getLastRms();if(d.getLastPeak()>offMaxPeak)offMaxPeak=d.getLastPeak();}}private void finishOffWindow(){captureTotals();lastOff="OFF f:"+offFrames+" pk:"+offMaxPeak+" rms:"+Math.round(offMaxRms)+" max:"+Math.round(offMaxScore*100f)+"%";getSharedPreferences("jarvis_hybrid",MODE_PRIVATE).edit().putString("wake_diag_off_last",lastOff).apply();}private void writeDiag(){OpenWakeWordDetector d=detector;if(d==null)return;captureTotals();long age=Math.max(0,System.currentTimeMillis()-d.getLastAudioAt());int score=Math.round(d.getLastScore()*100f),max=Math.round(globalMaxScore*100f),rms=Math.round(d.getLastRms());long eh=Math.max(0,d.getSpeechEnergyUntil()-System.currentTimeMillis());String live=(screenOff?"KAPALI":"ACIK")+" "+sourceName(d.getActiveSource())+" f:"+d.getFrameCount()+" pk:"+d.getLastPeak()+" rms:"+rms+" sc:"+score+"% Gmax:"+max+"% gate:"+d.getLastGate()+" eh:"+eh+" age:"+age+" rs:"+detectorStarts+" er:"+detectorErrors;String state=live+" | "+lastOff;getSharedPreferences("jarvis_hybrid",MODE_PRIVATE).edit().putString("wake_diag_last",state).apply();update(state);}
 private void shutdown(){paused=true;main.removeCallbacks(diagTick);if(detector!=null){detector.release();detector=null;}stopWakeAudio();releaseLock(cpuLock);releaseLock(handoffLock);releaseLock(screenLock);main.removeCallbacksAndMessages(null);}
 private void releaseLock(PowerManager.WakeLock l){if(l!=null&&l.isHeld())try{l.release();}catch(Exception ignored){}}
 private void wake(final float score){if(paused)return;JarvisForensics.event(this,"W","WAKE score="+Math.round(score*100f)+" rms="+(detector==null?-1:Math.round(detector.getLastRms()))+" frame="+(detector==null?-1:detector.getFrameCount())+" screenOff="+screenOff);if(score>globalMaxScore)globalMaxScore=score;if(screenOff&&score>offMaxScore)offMaxScore=score;paused=true;stopDetector("wake_detected");if(handoffLock!=null)try{handoffLock.acquire(20000L);}catch(Exception ignored){}update("Hey Jarvis algılandı · sesli yanıt hazırlanıyor");playWakeAcknowledgement(score);}
 private void playWakeAcknowledgement(final float score){stopWakeAudio();try{if(audio!=null)audio.requestAudioFocus(focusListener,AudioManager.STREAM_MUSIC,AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK);final MediaPlayer p=new MediaPlayer();wakePlayer=p;p.setAudioStreamType(AudioManager.STREAM_MUSIC);AssetFileDescriptor afd=getAssets().openFd("voice/wake.mp3");try{p.setDataSource(afd.getFileDescriptor(),afd.getStartOffset(),afd.getLength());}finally{afd.close();}p.setOnCompletionListener(new MediaPlayer.OnCompletionListener(){public void onCompletion(MediaPlayer mp){finishWakeAudio(p);openCommand(score);}});p.setOnErrorListener(new MediaPlayer.OnErrorListener(){public boolean onError(MediaPlayer mp,int what,int extra){finishWakeAudio(p);openCommand(score);return true;}});p.prepare();p.start();update("Uyandım · komut dinleme açılıyor");}catch(Exception e){stopWakeAudio();openCommand(score);}}
 private void finishWakeAudio(MediaPlayer p){try{p.reset();}catch(Exception ignored){}try{p.release();}catch(Exception ignored){}if(wakePlayer==p)wakePlayer=null;if(audio!=null)try{audio.abandonAudioFocus(focusListener);}catch(Exception ignored){}}
 private void stopWakeAudio(){MediaPlayer p=wakePlayer;wakePlayer=null;if(p!=null){try{p.stop();}catch(Exception ignored){}try{p.reset();}catch(Exception ignored){}try{p.release();}catch(Exception ignored){}}if(audio!=null)try{audio.abandonAudioFocus(focusListener);}catch(Exception ignored){}}
 private void wakeDisplay(){try{PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);if(pm!=null&&!pm.isInteractive()&&screenLock!=null&&!screenLock.isHeld())screenLock.acquire(7000L);}catch(Exception ignored){}}
 private void openCommand(final float score){wakeDisplay();speechLease=false;Intent open=new Intent(this,HybridActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP).putExtra(EXTRA_WAKE,true).putExtra(EXTRA_WAKE_ACKED,true).putExtra("wake_score",score);boolean launchRequested=false;try{startActivity(open);launchRequested=true;JarvisForensics.event(this,"W","openCommand startActivity requested");}catch(Exception e){JarvisForensics.event(this,"W","openCommand startActivity FAILED "+e.getClass().getSimpleName());PendingIntent pi=PendingIntent.getActivity(this,1700,open,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0));NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null)nm.notify(NOTIFICATION_ID,notificationWithIntent("JARVIS seni duydu · komut için dokun",pi));}main.postDelayed(new Runnable(){public void run(){releaseLock(handoffLock);}},8000L);final boolean requested=launchRequested;main.postDelayed(new Runnable(){public void run(){if(!paused)return;if(speechLease){JarvisForensics.event(WakeWordService.this,"W","handoff guard OK speechLease active");return;}JarvisForensics.event(WakeWordService.this,"W","handoff guard fallback requested="+requested);paused=false;startDetector("handoff_no_speech_ack");}},8500L);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null){NotificationChannel c=new NotificationChannel(CHANNEL,"JARVIS Wake Word",NotificationManager.IMPORTANCE_LOW);c.setDescription("Ekran kapalıyken çevrimdışı Hey Jarvis wake word dinleme");c.setSound(null,null);nm.createNotificationChannel(c);}}}
 private Notification notification(String text){Intent open=new Intent(this,HybridActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent pi=PendingIntent.getActivity(this,1,open,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0));return notificationWithIntent(text,pi);}
 private Notification notificationWithIntent(String text,PendingIntent pi){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setContentTitle("JARVIS · Always-On").setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setSmallIcon(android.R.drawable.ic_btn_speak_now).setOngoing(true).setOnlyAlertOnce(true).setContentIntent(pi).setCategory(Notification.CATEGORY_SERVICE);if(Build.VERSION.SDK_INT<26)b.setPriority(Notification.PRIORITY_LOW);return b.build();}
 private void update(String text){String full=text+"\n"+JarvisForensics.tail(this,5);NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null)nm.notify(NOTIFICATION_ID,notification(full));}
 @Override public void onTaskRemoved(Intent rootIntent){JarvisForensics.event(this,"L","service.onTaskRemoved");super.onTaskRemoved(rootIntent);}@Override public void onTrimMemory(int level){JarvisForensics.event(this,"L","service.onTrimMemory level="+level);super.onTrimMemory(level);}@Override public void onDestroy(){JarvisForensics.event(this,"L","service.onDestroy paused="+paused+" running="+(detector!=null&&detector.isRunning()));try{unregisterReceiver(control);}catch(Exception ignored){}shutdown();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
