package com.hakan.jarvis;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.content.res.AssetFileDescriptor;import android.media.*;import android.os.*;
public final class WakeWordService extends Service{
 public static final String ACTION_START="com.hakan.jarvis.WAKE_START",ACTION_STOP="com.hakan.jarvis.WAKE_STOP",ACTION_PAUSE="com.hakan.jarvis.WAKE_PAUSE",ACTION_RESUME="com.hakan.jarvis.WAKE_RESUME",EXTRA_WAKE="jarvis_wake",EXTRA_WAKE_ACKED="jarvis_wake_acked";private static final String CHANNEL="jarvis_wake_channel";private static final int NOTIFICATION_ID=1700;private final Handler main=new Handler(Looper.getMainLooper());private OpenWakeWordDetector detector;private PowerManager.WakeLock cpuLock,handoffLock,screenLock;private MediaPlayer wakePlayer;private AudioManager audio;private boolean paused;
 private final AudioManager.OnAudioFocusChangeListener focusListener=new AudioManager.OnAudioFocusChangeListener(){public void onAudioFocusChange(int f){}};
 private final BroadcastReceiver control=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String a=i==null?"":i.getAction();if(ACTION_PAUSE.equals(a)){paused=true;stopDetector();update("Komut mikrofonu aktif · wake beklemede");}else if(ACTION_RESUME.equals(a)){if(enabled(WakeWordService.this)){paused=false;startDetector();}}else if(ACTION_STOP.equals(a)){shutdown();stopForeground(true);stopSelf();}}};
 public static boolean enabled(Context c){return c.getSharedPreferences("jarvis_hybrid",Context.MODE_PRIVATE).getBoolean("wake_enabled",true);}
 private static void signal(Context c,String action){try{c.sendBroadcast(new Intent(action).setPackage(c.getPackageName()));}catch(Exception ignored){}}
 public static void ensureStarted(Context c){if(!enabled(c)||c.checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)return;Intent i=new Intent(c,WakeWordService.class).setAction(ACTION_START);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 public static void stop(Context c){signal(c,ACTION_STOP);try{c.stopService(new Intent(c,WakeWordService.class));}catch(Exception ignored){}}
 public static void pause(Context c){signal(c,ACTION_PAUSE);}
 public static void resume(Context c){if(enabled(c))signal(c,ACTION_RESUME);}
 @Override public void onCreate(){super.onCreate();createChannel();try{registerReceiver(control,new IntentFilter(ACTION_PAUSE));registerReceiver(control,new IntentFilter(ACTION_RESUME));registerReceiver(control,new IntentFilter(ACTION_STOP));}catch(Exception ignored){}PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);if(pm!=null){cpuLock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"JARVIS:wakeword");cpuLock.setReferenceCounted(false);handoffLock=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"JARVIS:wake-handoff");handoffLock.setReferenceCounted(false);screenLock=pm.newWakeLock(PowerManager.SCREEN_DIM_WAKE_LOCK|PowerManager.ACQUIRE_CAUSES_WAKEUP|PowerManager.ON_AFTER_RELEASE,"JARVIS:wake-screen");screenLock.setReferenceCounted(false);}audio=(AudioManager)getSystemService(AUDIO_SERVICE);}
 @Override public int onStartCommand(Intent intent,int flags,int startId){startForeground(NOTIFICATION_ID,notification("'Hey Jarvis' demeni bekliyor"));if(!enabled(this)){stopSelf();return START_NOT_STICKY;}paused=false;startDetector();return START_STICKY;}
 private void startDetector(){if(paused||!enabled(this)||checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)return;if(cpuLock!=null&&!cpuLock.isHeld())try{cpuLock.acquire();}catch(Exception ignored){}if(detector==null)detector=new OpenWakeWordDetector(this,0.32f,0.50f,3500L);if(detector.isRunning())return;update("Offline wake aktif · 'Hey Jarvis' bekleniyor");detector.start(new OpenWakeWordDetector.Listener(){public void onDetected(float score){wake(score);}public void onError(String m){update("Wake motoru yeniden hazırlanıyor");main.postDelayed(new Runnable(){public void run(){if(!paused)startDetector();}},2500);}});}
 private void stopDetector(){if(detector!=null)detector.stop();if(cpuLock!=null&&cpuLock.isHeld())try{cpuLock.release();}catch(Exception ignored){}}
 private void shutdown(){paused=true;if(detector!=null){detector.release();detector=null;}stopWakeAudio();releaseLock(cpuLock);releaseLock(handoffLock);releaseLock(screenLock);main.removeCallbacksAndMessages(null);}
 private void releaseLock(PowerManager.WakeLock l){if(l!=null&&l.isHeld())try{l.release();}catch(Exception ignored){}}
 private void wake(final float score){if(paused)return;paused=true;stopDetector();if(handoffLock!=null)try{handoffLock.acquire(20000L);}catch(Exception ignored){}update("Hey Jarvis algılandı · sesli yanıt hazırlanıyor");playWakeAcknowledgement(score);}
 private void playWakeAcknowledgement(final float score){stopWakeAudio();try{if(audio!=null)audio.requestAudioFocus(focusListener,AudioManager.STREAM_MUSIC,AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK);final MediaPlayer p=new MediaPlayer();wakePlayer=p;p.setAudioStreamType(AudioManager.STREAM_MUSIC);AssetFileDescriptor afd=getAssets().openFd("voice/wake.mp3");try{p.setDataSource(afd.getFileDescriptor(),afd.getStartOffset(),afd.getLength());}finally{afd.close();}p.setOnCompletionListener(new MediaPlayer.OnCompletionListener(){public void onCompletion(MediaPlayer mp){finishWakeAudio(p);openCommand(score);}});p.setOnErrorListener(new MediaPlayer.OnErrorListener(){public boolean onError(MediaPlayer mp,int what,int extra){finishWakeAudio(p);openCommand(score);return true;}});p.prepare();p.start();update("Uyandım · komut dinleme açılıyor");}catch(Exception e){stopWakeAudio();openCommand(score);}}
 private void finishWakeAudio(MediaPlayer p){try{p.reset();}catch(Exception ignored){}try{p.release();}catch(Exception ignored){}if(wakePlayer==p)wakePlayer=null;if(audio!=null)try{audio.abandonAudioFocus(focusListener);}catch(Exception ignored){}}
 private void stopWakeAudio(){MediaPlayer p=wakePlayer;wakePlayer=null;if(p!=null){try{p.stop();}catch(Exception ignored){}try{p.reset();}catch(Exception ignored){}try{p.release();}catch(Exception ignored){}}if(audio!=null)try{audio.abandonAudioFocus(focusListener);}catch(Exception ignored){}}
 private void wakeDisplay(){try{PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);if(pm!=null&&!pm.isInteractive()&&screenLock!=null&&!screenLock.isHeld())screenLock.acquire(7000L);}catch(Exception ignored){}}
 private void openCommand(final float score){wakeDisplay();Intent open=new Intent(this,HybridActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP).putExtra(EXTRA_WAKE,true).putExtra(EXTRA_WAKE_ACKED,true).putExtra("wake_score",score);try{startActivity(open);}catch(Exception e){PendingIntent pi=PendingIntent.getActivity(this,1700,open,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0));NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null)nm.notify(NOTIFICATION_ID,notificationWithIntent("JARVIS seni duydu · komut için dokun",pi));}main.postDelayed(new Runnable(){public void run(){releaseLock(handoffLock);}},8000L);main.postDelayed(new Runnable(){public void run(){if(paused){paused=false;startDetector();}}},20000L);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null){NotificationChannel c=new NotificationChannel(CHANNEL,"JARVIS Wake Word",NotificationManager.IMPORTANCE_LOW);c.setDescription("Ekran kapalıyken çevrimdışı Hey Jarvis wake word dinleme");c.setSound(null,null);nm.createNotificationChannel(c);}}}
 private Notification notification(String text){Intent open=new Intent(this,HybridActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent pi=PendingIntent.getActivity(this,1,open,PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE:0));return notificationWithIntent(text,pi);}
 private Notification notificationWithIntent(String text,PendingIntent pi){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setContentTitle("JARVIS · Always-On").setContentText(text).setSmallIcon(android.R.drawable.ic_btn_speak_now).setOngoing(true).setOnlyAlertOnce(true).setContentIntent(pi).setCategory(Notification.CATEGORY_SERVICE);if(Build.VERSION.SDK_INT<26)b.setPriority(Notification.PRIORITY_LOW);return b.build();}
 private void update(String text){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(nm!=null)nm.notify(NOTIFICATION_ID,notification(text));}
 @Override public void onDestroy(){try{unregisterReceiver(control);}catch(Exception ignored){}shutdown();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
